mkdir configs/tianchi_bp

mv configs/tianchi_configs/faster_rcnn_r50_fpn_ms576_as16_slice3_lesion_1x.py configs/tianchi_bp
mv configs/tianchi_configs/faster_rcnn_r50_fpn_ms576_as16_slice3_msb_lesion_1x.py configs/tianchi_bp
mv configs/tianchi_configs/faster_rcnn_r3d50_fpn_ms576_as16_slice7_lesion_scratch_1x.py configs/tianchi_bp
mv configs/tianchi_configs/faster_rcnn_r50_fpn_ms576_as16_slice9_lesion_1x.py configs/tianchi_bp
mv configs/tianchi_configs/faster_rcnn_r50_fpn_slice27_lesion_1x.py configs/tianchi_bp
mv configs/tianchi_configs/MVPNet_r50_fpn_ms576_as16_slice3_lesion_1x.py configs/tianchi_bp
mv configs/tianchi_configs/MVPNet_r50_fpn_ms576_as16_slice9_lesion_1x.py configs/tianchi_bp
mv configs/tianchi_configs/two_stream_ms576_as16_nonlocal_scratch_1x.py configs/tianchi_bp
